version: '3.9'
services:
  prod:
    build: 
      context: .
      dockerfile: .\Dockerfile_prod 
    ports:
      - "80:9001"
  dev:
    build: 
      context: .
      dockerfile: .\Dockerfile 
    volumes:
      - ./static:/static 
    ports:
      - "9001:9001"