
ARG USER=neoflex

FROM golang:1.17.0-alpine as builder

WORKDIR /go/src/app

COPY main.go go.mod ./

ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64


ARG USER
ENV USER=$USER
#ENV USER=appuser
ENV UID=10001


RUN adduser \
--disabled-password \
--gecos "" \
--home "/nonexistent" \
--shell "/sbin/nologin" \
--no-create-home \
--uid "${UID}" \
"${USER}"
#WORKDIR $GOPATH/src/mypackage/myapp/



RUN apk update && apk add --no-cache git
RUN go mod download
RUN go mod verify
RUN go build -ldflags="-w -s" -o /go/bin/main

FROM alpine

COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group

ARG USER
ENV USER=$USER
USER $USER:$USER
EXPOSE 9001

ADD ./static /static/
COPY --from=builder /go/bin/main /
COPY start.sh /
#RUN apk add --no-cache libc6-compat


CMD [ "/main" ]


