apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
      app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: "docker.io/library/myapp:1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9001
              protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  type: NodePort
  ports:
    - port: 9001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: app