name: Docker and Helm Build and Push


on:
  push:
    branches:
      - master

# env:
#   CR_REGISTRY: crpfe65tgiohcnakbtfh
#   CR_REPO: prj-manager
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    #environment: dev
    steps:


      - name: Checkout code
        uses: actions/checkout@v2

        
      - name: Get latest tag
        id: latest_tag
        run: echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"

       
      - name: Get version
        id: getver
        run: |
          DATE=$(date +'%d-%m-%y')
          echo "GIT_VER=$(git describe --match "v*"  --abbrev=4 --tags --always `git rev-list --tags --max-count=1`)-$GITHUB_RUN_NUMBER-$DATE" >> $GITHUB_ENV
      - name: echo
        run: | 
              echo $GIT_VER
              echo $(git describe --abbrev=0 --tags)
      - name: Get latest tag
        run: |
            git fetch --tags
            latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
            echo "Latest tag: $latest_tag"
            
    outputs:
          GIT_VER: ${{ env.GIT_VER }}

  helm-deploy:
    runs-on: ubuntu-latest
    needs:  [build-and-push]
    #environment: dev
    env:
      GIT_VER: ${{ needs.build-and-push.outputs.GIT_VER }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: install yq
      uses: mikefarah/yq@v4.15.1

    - name: update infra yaml file
      run: |
        cd ops-tools/helm/app
        yq e -i '.image.tag="${{ env.GIT_VER }}"' values.yaml
        cat  values.yaml
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_message: deploy with image ${{ env.GIT_VER }}
          #token: ${{ github.token }}


    # - name: Deploy
    #   run: |
    #     cd ops-tools/helm/app
    #     sed -i 's/imageTag: .*/imageTag: latest/' values.yaml
    #     cat values.yaml
    # - name: Deploy
    #   uses: okar1/yc-helm@master
    #   with:
    #     SA_KEY: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
    #     K8S_CLUSTER_ID: catr6ctchebm3k7lpsfg
    #     HELM_ARGS: upgrade --install -n=prj-manager django ./ops-tools/helm/django --set image.repository=cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPO }},image.tag=${{ env.GIT_VER }}